INSERT INTO sala VALUES (sekwencja_sala.nextval, 'SALA 1', 400);
INSERT INTO sala VALUES (sekwencja_sala.nextval, 'SALA 2', 400);
INSERT INTO sala VALUES (sekwencja_sala.nextval, 'SALA 3', 300);
INSERT INTO sala VALUES (sekwencja_sala.nextval, 'SALA 4', 300);
INSERT INTO sala VALUES (sekwencja_sala.nextval, 'SALA 5', 500);
INSERT INTO sala VALUES (sekwencja_sala.nextval, 'SALA 6', 200);
INSERT INTO sala VALUES (sekwencja_sala.nextval, 'SALA 7', 200);
INSERT INTO gatunek_filmu VALUES (sekwencja_gatunek_filmu.nextval, 'Kryminal');
INSERT INTO gatunek_filmu VALUES (sekwencja_gatunek_filmu.nextval, 'Science-fiction');
INSERT INTO gatunek_filmu VALUES (sekwencja_gatunek_filmu.nextval, 'Fantasy');
INSERT INTO gatunek_filmu VALUES (sekwencja_gatunek_filmu.nextval, 'Komedia');
INSERT INTO gatunek_filmu VALUES (sekwencja_gatunek_filmu.nextval, 'Dramat');
INSERT INTO gatunek_filmu VALUES (sekwencja_gatunek_filmu.nextval, 'Musical');
INSERT INTO gatunek_filmu VALUES (sekwencja_gatunek_filmu.nextval, 'Wojenny');
INSERT INTO gatunek_filmu VALUES (sekwencja_gatunek_filmu.nextval, 'Akcja');
INSERT INTO gatunek_filmu VALUES (sekwencja_gatunek_filmu.nextval, 'Animowany');
INSERT INTO gatunek_filmu VALUES (sekwencja_gatunek_filmu.nextval, 'Historyczny');
INSERT INTO film VALUES (sekwencja_film.nextval, 'Hotel Transylvania', '');
INSERT INTO film VALUES (sekwencja_film.nextval, 'Jumanji', '');
INSERT INTO film VALUES (sekwencja_film.nextval, 'Szeregowiec Ryan', '');
INSERT INTO film VALUES (sekwencja_film.nextval, 'Klamca, klamca', '');
INSERT INTO film VALUES (sekwencja_film.nextval, 'Mamma Mia', '');
INSERT INTO film VALUES (sekwencja_film.nextval, 'Zielona Mila', 'Emerytowany straznik wiezienny opowiada przyjaciolce o niezwyklym mezczyznie, ktorego skazano na smierc za zabojstwo dwoch 9-letnich dziewczynek.');
INSERT INTO film VALUES (sekwencja_film.nextval, 'W cywilu', '');
INSERT INTO film VALUES (sekwencja_film.nextval, 'Gwiezdne Wojny: Powrot Jedi', '');
INSERT INTO film VALUES (sekwencja_film.nextval, 'Wladca Pierscieni: Dwie wieze', '');
INSERT INTO film VALUES (sekwencja_film.nextval, 'Shrek', 'By odzyskac swoj dom, brzydki ogr z gadatliwym oslem wyruszaja uwolnic piekna ksiezniczke.');
INSERT INTO film_gatunek VALUES (sekwencja_film_gatunek.nextval, 1, 4);
INSERT INTO film_gatunek VALUES (sekwencja_film_gatunek.nextval, 1, 9);
INSERT INTO film_gatunek VALUES (sekwencja_film_gatunek.nextval, 2, 3);
INSERT INTO film_gatunek VALUES (sekwencja_film_gatunek.nextval, 2, 8);
INSERT INTO film_gatunek VALUES (sekwencja_film_gatunek.nextval, 3, 7);
INSERT INTO film_gatunek VALUES (sekwencja_film_gatunek.nextval, 3, 8);
INSERT INTO film_gatunek VALUES (sekwencja_film_gatunek.nextval, 4, 4);
INSERT INTO film_gatunek VALUES (sekwencja_film_gatunek.nextval, 5, 6);
INSERT INTO film_gatunek VALUES (sekwencja_film_gatunek.nextval, 6, 3);
INSERT INTO film_gatunek VALUES (sekwencja_film_gatunek.nextval, 6, 5);
INSERT INTO seans VALUES (sekwencja_seans.nextval, '19/01/28', '17:00', 1, 1);
INSERT INTO seans VALUES (sekwencja_seans.nextval, '19/01/29', '17:00', 2, 2);
INSERT INTO seans VALUES (sekwencja_seans.nextval, '19/01/29', '20:00', 3, 3);
INSERT INTO seans VALUES (sekwencja_seans.nextval, '19/01/29', '20:00', 2, 5);
INSERT INTO seans VALUES (sekwencja_seans.nextval, '19/01/30', '17:00', 1, 4);
INSERT INTO seans VALUES (sekwencja_seans.nextval, '19/01/30', '20:00', 2, 5);
INSERT INTO seans VALUES (sekwencja_seans.nextval, '19/01/31', '20:00', 3, 6);
INSERT INTO seans VALUES (sekwencja_seans.nextval, '19/01/31', '20:00', 2, 4);
INSERT INTO adres (id, ulica, nr_domu, miejscowosc,kod_pocztowy) VALUES (sekwencja_adres.nextval, 'Krakowska', '90', 'Kielce', '25-012');
INSERT INTO adres (id, ulica, nr_domu, miejscowosc,kod_pocztowy) VALUES (sekwencja_adres.nextval, 'Warszawska', '4', 'Kielce', '25-123');
INSERT INTO adres (id, ulica, nr_domu, miejscowosc,kod_pocztowy) VALUES (sekwencja_adres.nextval, 'Dluga', '45', 'Kielce', '25-202');
INSERT INTO adres (id, ulica, nr_domu, miejscowosc,kod_pocztowy) VALUES (sekwencja_adres.nextval, 'Wrzosowa', '12', 'Kielce', '25-111');
INSERT INTO adres (id, ulica, nr_domu, miejscowosc,kod_pocztowy) VALUES (sekwencja_adres.nextval, 'Jesionowa', '112', 'Kielce', '25-000');
INSERT INTO kupujacy VALUES (sekwencja_kupujacy.nextval, 'Jan', 'Kowalski', '', 1);
INSERT INTO kupujacy VALUES (sekwencja_kupujacy.nextval, 'Janina', 'Kowalska', '', 1);
INSERT INTO kupujacy VALUES (sekwencja_kupujacy.nextval, 'Andrzej', 'Nowak', '', 3);
INSERT INTO kupujacy VALUES (sekwencja_kupujacy.nextval, 'Jerzy', 'Wojtasinski', '', 4);
INSERT INTO kupujacy VALUES (sekwencja_kupujacy.nextval, 'Anna', 'Kos', '', 5);
INSERT INTO promocja VALUES (sekwencja_promocja.nextval, 'swiateczna promocja', 'Kup 4 bilety w cenie 3', 33);
INSERT INTO promocja VALUES (sekwencja_promocja.nextval, 'We dwoje', 'Promocja dla par', 50);
INSERT INTO promocja VALUES (sekwencja_promocja.nextval, 'Dla dzieci', '20% znizki', 20);
INSERT INTO promocja VALUES (sekwencja_promocja.nextval, 'Dla studentow', 'Znizka dla studentow z wazna legitymacja', 30);
INSERT INTO promocja VALUES (sekwencja_promocja.nextval, 'Dla seniorow', 'Promocja dla seniorow od 60 lat', 60);
INSERT INTO rodzaj_biletu VALUES (sekwencja_rodzaj_biletu.nextval, 'Normalny', '');
INSERT INTO rodzaj_biletu VALUES (sekwencja_rodzaj_biletu.nextval, 'Ulgowy', 'Uprawnia do znizki');
INSERT INTO rodzaj_biletu VALUES (sekwencja_rodzaj_biletu.nextval, 'Na seans 3D', 'Dotyczy wszystkich filmow 3D');
INSERT INTO rodzaj_biletu VALUES (sekwencja_rodzaj_biletu.nextval, 'Grupowy', 'Min. 10 osob');
INSERT INTO rodzaj_biletu VALUES (sekwencja_rodzaj_biletu.nextval, 'Rodzinny', 'Min. 3 osoby');
INSERT INTO rodzaj_biletu VALUES (sekwencja_rodzaj_biletu.nextval, 'Dla par', '');
INSERT INTO dzien_tygodnia VALUES (sekwencja_dzien_tygodnia.nextval, 'poniedzialek');
INSERT INTO dzien_tygodnia VALUES (sekwencja_dzien_tygodnia.nextval, 'wtorek');
INSERT INTO dzien_tygodnia VALUES (sekwencja_dzien_tygodnia.nextval, 'sroda');
INSERT INTO dzien_tygodnia VALUES (sekwencja_dzien_tygodnia.nextval, 'czwartek');
INSERT INTO dzien_tygodnia VALUES (sekwencja_dzien_tygodnia.nextval, 'piatek');
INSERT INTO dzien_tygodnia VALUES (sekwencja_dzien_tygodnia.nextval, 'sobota');
INSERT INTO dzien_tygodnia VALUES (sekwencja_dzien_tygodnia.nextval, 'niedziela');
INSERT INTO dzien_tygodnia VALUES (sekwencja_dzien_tygodnia.nextval, 'swieto');
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 1, 1, 25, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 1, 2, 25, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 1, 3, 25, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 1, 4, 25, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 1, 5, 23, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 1, 6, 23, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 1, 7, 23, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 1, 8, 20, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 2, 1, 23, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 2, 2, 23, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 2, 3, 23, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 2, 4, 23, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 2, 5, 21, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 2, 6, 21, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 2, 7, 21, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 2, 8, 18, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 3, 1, 27, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 3, 2, 27, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 3, 3, 27, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 3, 4, 27, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 3, 5, 25, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 3, 6, 25, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 3, 7, 25, 2019);
INSERT INTO cennik VALUES (sekwencja_cennik.nextval, 3, 8, 23, 2019);
INSERT INTO bilet VALUES (sekwencja_bilet.nextval, 1, 3, NULL, 1);
INSERT INTO bilet VALUES (sekwencja_bilet.nextval, 1, 3, NULL, NULL);
INSERT INTO bilet VALUES (sekwencja_bilet.nextval, 1, 3, NULL, 2);
INSERT INTO bilet VALUES (sekwencja_bilet.nextval, 2, 4, 4, NULL);
INSERT INTO bilet VALUES (sekwencja_bilet.nextval, 2, 4, 4, NULL);